### ISSUE TITLE
Can't open a file... on windows10

### ISSUE THREAD

**Issue by ghost** [Tirlititi/Hades-Workshop#2]
Hello, sorry if this is not the right section for this but I could not find any answer to that issue.

![image](https://user-images.githubusercontent.com/31047394/29332846-c1b1f944-8201-11e7-8682-20075ecaf2f2.png)

I tried to open p0data2.bin to see how the tool looks, a window asked me for a scan which I answered yes.

This is annoying because the tools sounds great and powerful from what I've read. But somehow I'm not able to use it yet. Any idea what could be wrong ? Am I missing something on my computer ?
 Any help would be appreciated, thanks in advance, also my apologies for bad english.

**Comment by Tirlititi** [comment]
For the record, the file that should be opened directly is always "FF9_Launcher.exe" on PC.
Opening .bin file should only be done for opening the PSX iso files.
